config/routes.rb
Rails.application.routes.draw do
  root "pages#welcome"
  get '/portfolio' => 'pages#portfolio'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  def portfolio
  end
  def about
  end
  def contact
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  
  def home
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,500,700" rel="stylesheet">	
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" src=".../assets/stylesheets/unslider.css">
  
  <title>Portfolio</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class= "header">
   
   <%= link_to "Welcome", root_path %>
    <%= link_to "Blog", "https://medium.com/@karinaschlossergaulin/learning-to-code-is-a-bitch-dc1fff485792#.9myve1adm", target: "_blank" %>
    <%= link_to "About", about_path %>
    <%= link_to "Contact", contact_path %>

  	<div class="container">
    	<h1>Karina Gaulin</h1>
      	<ul>
          <li>About</li>
          <li>Contact</li>
        </ul>
      </div>
  </div>
	<div class="main">
    <div class="container">
    <%= yield %>
    </div>
  </div>
  <div class="footer">
      <div class="container">
   			<a href="https://www.facebook.com/?stype=lo&jlou=AffHN7M5ZJWc9QenxLQ283Y1uf3Pj7rRLYp00-QotR4aA5S8cxIu4s9PplmKcM4pHdxnt-zYMKc-rMYymGwsUUWEPs4rjlQZ8bV7M9RsnJNNmA&smuh=50340&lh=Ac8pajQJWzqENsfu">
       
  			<%=image_tag("http://image.flaticon.com/icons/svg/33/33702.svg")%>
      	</a>
      </div>
   </div>
  <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src=".../assets/javascripts/unslider.js"></script> <!-- but with the right path! -->
    <script>
		jQuery(document).ready(function($) {
			$('.banner').unslider();
		});
	</script>
</body>
</html>

app/views/pages/about.html.erb
<img src="https://photos-6.dropbox.com/t/2/AAB4dOIhkdCKbp9g8SD3ilk-WugwsTVBaj2m1eOEoDQnFQ/12/627322166/jpeg/32x32/1/_/1/2/WIN_20161201_09_06_47_Pro.jpg/EOmP64oFGAIgBygH/JThPju8E7Not4FX6RlNe-LdTqO9l1ZRpqDTEiWcOOnI?size=1280x960&size_mode=3"/>
<h2>My name is Karina Gaulin. I am currently working as a Library Circulation Assistant while I learn Web Development.

app/views/pages/contact.html.erb
<a href="karinagaulin@gmail.com">Email</a>
<a href="https://www.facebook.com/karina.schlossergaulin">Facebook</a>
<a href="https://twitter.com/kgau73">Twitter</a>

app/views/pages/portfolio.html.erb
<div class="banner">
	<ul>
    <li><img src="https://dl.dropboxusercontent.com/s/xovmef479axdshh/Screen%20Shot%202016-02-06%20at%2011.12.07%20AM.png?dl=0" class="img-responsive"></li>
		<li><img src="https://dl.dropboxusercontent.com/s/igzvw95ufwlxtrx/Screen%20Shot%202016-02-06%20at%2011.12.29%20AM.png?dl=0" class="img-responsive"></li>
		<li><img src="https://dl.dropboxusercontent.com/s/lhbuwd60mmc1pc3/Screen%20Shot%202016-02-06%20at%2011.13.02%20AM.png?dl=0" class="img-responsive"></li>
 	</ul>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <a href="#">
        <img class="img-responsive" src="https://app.box.com/representation/file_version_115299396072/image_2048/1.png">
      </a>
      <p>Bass. Shows albums with links to tracks</p>
    </div>
    <div class="col-md-4">
      <a href="#"><img class="img-responsive" src="https://app.box.com/representation/file_version_115301563755/image_2048/1.png"></a>
      <p>Bookmarks. A rating and review system</p>
    </div>
    <div class="col-md-4">
      <a href="#"><img class="img-responsive" src="https://app.box.com/representation/file_version_115300713896/image_2048/1.png"></a>
      <p>Threadly. A comment saving app.</p>
    </div>
 </div>
  
  
  </div>

app/views/pages/welcome.html.erb
<%= link_to "Portfolio", portfolio_path%>
 
	<h1>I am a Front-end Web Developer with 1 year of experiece in HTML, CSS, JavaScript, jQuerry, Ruby, Ruby on Rails, SASS, Git and Command Line.	</h1>
      <button type="button">View My Work</button>
 